# Use Alpine version of Python 3.12
FROM python:3.12-alpine

# Set environment variables for Python
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PIP_NO_CACHE_DIR 1

# Set working directory
WORKDIR /app

# Copy current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install --upgrade pip && \
	pip install --no-cache-dir --upgrade -r requirements.txt && \

# Expose ports and define startup commands based on selected framework
EXPOSE {{ port }}
{% if framework == 'django' %}
# Specify the entry point
CMD ["python", "manage.py", "runserver"]

{% elif framework == 'fastapi' %}
# Specify the entry point (Replace "mail" with your actual file name)
CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--reload"]

{% elif framework == 'flask' %}
# Specify the entry point
CMD ["flask", "run"]

{% elif framework == 'pyramid' %}
# Specify the entry point
CMD ["pserve", "development.ini"]

{% elif framework == 'flacon' %}
# Specify the entry point
CMD ["gunicorn", "app:api", "-b", "0.0.0.0:8000"]
{% endif %}